# Generated by Django 2.0.5 on 2019-05-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='additional_info',
            field=models.CharField(help_text='Additional Info', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='campus',
            field=models.CharField(help_text='Campus', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.CharField(help_text='Credit', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(help_text='Department', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(help_text='Instructor', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='room',
            field=models.CharField(help_text='Times', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(help_text='Semester', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='times',
            field=models.CharField(help_text='Times', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Title', max_length=200),
        ),
    ]
