# Generated by Django 2.0.5 on 2019-05-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20190524_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='additional_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='misc_links',
            field=models.TextField(),
        ),
    ]
