# Generated by Django 2.2.1 on 2019-05-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20190524_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AlterField(
            model_name='question',
            name='details',
            field=models.CharField(default='SOME STRING', help_text='Question Details', max_length=3000),
        ),
    ]
