# Generated by Django 2.2.1 on 2019-05-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
