# Generated by Django 2.2.1 on 2019-06-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20190524_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.CharField(default='Question default string', help_text='Question', max_length=140),
        ),
    ]
