# Generated by Django 2.2.1 on 2019-05-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
