# Generated by Django 2.2.1 on 2019-06-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20190605_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtags', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ManyToManyField(to='newapp.Subtag')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='newapp.Tag'),
        ),
    ]
