# Generated by Django 2.2.1 on 2019-06-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20190614_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='subtags',
            field=models.ManyToManyField(to='newapp.Subtag'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
